// Municipal data with EXACT figures and unique editorial content
module.exports = [
{slug:"extremadura/caceres/plasencia",nombre:"Plasencia",prov:"Cáceres",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.65,ibiR:0.52,basura:95,periodo:"1 oct – 30 nov 2026",
bonFN:"Hasta 30%",bonSolar:"30%",poblacion:"40.068",
fuente:"DOE nº 243, 20/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://plasencia.sedelectronica.es",
intro:"Plasencia, segunda ciudad de la provincia de Cáceres con 40.068 habitantes según el INE (2025), se sitúa en la confluencia del río Jerte con el Valle de la Vera. Su casco histórico amurallado, declarado Conjunto Histórico-Artístico, alberga una catedral doble única en España. La ciudad ejerce de capital comarcal del norte de Extremadura, con un mercado inmobiliario estable donde los valores catastrales oscilan entre 35.000 € en el casco antiguo y 75.000 € en las urbanizaciones de la zona sur (Los Pinos, Miralvalle).",
contextoIBI:"El tipo del 0,65% se mantiene estable desde 2022. En la última ponencia de valores (2018), el Catastro revisó al alza un 12% los inmuebles del casco antiguo, lo que provocó subidas de recibo sin que el Ayuntamiento modificara el tipo. Los pisos de 2-3 dormitorios en la zona centro tienen valores catastrales medios de 50.000-60.000 €, lo que sitúa la cuota anual entre 325 € y 390 €.",
contextoBasura:"El importe de 95 €/año para vivienda habitual corresponde a la tarifa doméstica general aprobada en la ordenanza fiscal nº 3.01. Los locales comerciales pagan entre 180 € y 450 € según superficie. El servicio de recogida opera 6 días/semana en el casco y zonas urbanas, con contenedores de fracción orgánica desde enero de 2026 por exigencia de la Ley 7/2022.",
contextoPlusvalia:"Plasencia presenta un mercado de transmisiones activo, especialmente en herencias de patrimonio urbano familiar. El valor catastral del suelo representa aproximadamente el 45% del valor catastral total en la mayoría de inmuebles del casco. Para una vivienda heredada con 15 años de tenencia, el coeficiente municipal vigente es 0,09 (inferior al máximo legal de 0,10).",
consejo:"Si tienes un inmueble en el casco histórico con calificación BIC, puedes solicitar bonificación de hasta el 90% del IBI presentando certificado de Patrimonio. Además, la oficina de recaudación de la Diputación de Cáceres (en Avda. Virgen del Puerto) gestiona el fraccionamiento del IBI en 2 plazos sin intereses si lo solicitas antes del 15 de septiembre.",
valoresCatastrales:[{desc:"Piso 2 hab. casco antiguo",vc:38000},{desc:"Piso 3 hab. zona centro",vc:55000},{desc:"Chalet adosado zona sur",vc:78000},{desc:"Piso nuevo Miralvalle",vc:95000}]},

{slug:"extremadura/caceres/navalmoral-de-la-mata",nombre:"Navalmoral de la Mata",prov:"Cáceres",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.62,ibiR:0.50,basura:88,periodo:"1 oct – 30 nov 2026",
bonFN:"25%",bonSolar:"25%",poblacion:"17.344",
fuente:"DOE nº 241, 18/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://navalmoral.sedelectronica.es",
intro:"Navalmoral de la Mata, con 17.344 habitantes, es el centro neurálgico del Campo Arañuelo cacereño y nudo de comunicaciones entre Madrid y Extremadura gracias a la A-5 y la línea ferroviaria. Su economía combina agricultura (tabaco, tomate) con industria agroalimentaria y servicios. El mercado inmobiliario es asequible: un piso de 3 dormitorios se mueve entre 60.000 € y 100.000 € de precio de mercado.",
contextoIBI:"El tipo del 0,62% es ligeramente inferior a la media provincial. Los valores catastrales no se han revisado desde 2015, por lo que están significativamente por debajo del valor de mercado (ratio catastral/mercado del 38%). Un piso tipo de 80 m² en el centro tiene un valor catastral medio de 42.000 €, con una cuota anual de 260 €.",
contextoBasura:"La tarifa de 88 €/año para vivienda habitual refleja la contención de costes gracias al convenio comarcal de gestión de residuos del Campo Arañuelo. Los inmuebles desocupados acreditados pueden solicitar una reducción del 50% presentando certificado de no habitabilidad.",
contextoPlusvalia:"El mercado inmobiliario de Navalmoral ha experimentado una ligera recuperación desde 2023. Las transmisiones hereditarias son frecuentes en el entorno rural periurbano. El coeficiente municipal para el método objetivo está fijado al máximo legal en todos los tramos.",
consejo:"Si compraste una vivienda antes de 2015 y el Catastro no ha revisado tu zona, tu valor catastral puede estar desactualizado a tu favor. Antes de solicitar una revisión catastral, valora si te compensa: una revisión al alza aumentaría tu IBI. La oficina de Catastro más cercana está en Cáceres capital.",
valoresCatastrales:[{desc:"Piso 2 hab. centro",vc:35000},{desc:"Piso 3 hab. barrio nuevo",vc:48000},{desc:"Casa pueblo reformada",vc:42000},{desc:"Chalet urbanización",vc:72000}]},

{slug:"extremadura/caceres/coria",nombre:"Coria",prov:"Cáceres",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.62,ibiR:0.50,basura:82,periodo:"1 oct – 30 nov 2026",
bonFN:"20%",bonSolar:"25%",poblacion:"12.842",
fuente:"DOE nº 240, 17/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://coria.sedelectronica.es",
intro:"Coria, ciudad episcopal con 12.842 habitantes, se asienta sobre un cerro junto al río Alagón en el noroeste cacereño. Su catedral gótico-renacentista y su recinto amurallado romano-medieval configuran un casco histórico de notable valor patrimonial. La ciudad sirve de cabecera comarcal del Valle del Alagón, con un mercado inmobiliario de precio bajo donde se pueden encontrar viviendas desde 40.000 €.",
contextoIBI:"El tipo del 0,62% se sitúa en la media provincial. La última revisión catastral data de 2013. Los inmuebles del casco histórico tienen valores catastrales particularmente bajos (25.000-35.000 €) debido a su antigüedad y estado de conservación, mientras que las viviendas nuevas en la zona de expansión alcanzan los 55.000-65.000 €.",
contextoBasura:"Con 82 €/año, Coria tiene una de las tasas de basuras más bajas de la provincia. El servicio se gestiona a través de la Mancomunidad de Municipios del Valle del Alagón, lo que permite economías de escala. No existe tarifa diferenciada para comercios pequeños de menos de 50 m².",
contextoPlusvalia:"Las transmisiones en Coria son mayoritariamente hereditarias. El bajo valor catastral del suelo hace que las cuotas de plusvalía sean moderadas incluso en propiedades mantenidas durante décadas.",
consejo:"Los inmuebles situados dentro del recinto amurallado pueden solicitar la bonificación por Conjunto Histórico si acreditan inversión en conservación. La bonificación puede llegar al 50% del IBI y es compatible con la de domiciliación bancaria.",
valoresCatastrales:[{desc:"Piso casco histórico",vc:28000},{desc:"Piso 3 hab. zona nueva",vc:45000},{desc:"Casa pueblo",vc:32000},{desc:"Vivienda unifamiliar",vc:58000}]},

{slug:"extremadura/caceres/trujillo",nombre:"Trujillo",prov:"Cáceres",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.61,ibiR:0.48,basura:78,periodo:"1 oct – 30 nov 2026",
bonFN:"20%",bonSolar:"25%",poblacion:"9.646",
fuente:"DOE nº 242, 19/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://trujillo.sedelectronica.es",
intro:"Trujillo, cuna de conquistadores como Francisco Pizarro, cuenta con 9.646 habitantes y un patrimonio monumental excepcional. Su Plaza Mayor, el castillo árabe y los numerosos palacios renacentistas hacen de la ciudad un destino turístico relevante en Extremadura. El mercado inmobiliario es dual: precios muy bajos en el casco alto (casas desde 20.000 €) y moderados en la zona nueva.",
contextoIBI:"El tipo del 0,61% es de los más bajos de la provincia. El casco monumental presenta valores catastrales muy reducidos por la antigüedad de las construcciones. En la zona de expansión (carretera de Madrid), los valores son más acordes al mercado actual.",
contextoBasura:"La tarifa de 78 €/año es la más baja de los municipios cacereños de nuestra guía, reflejo del menor coste operativo derivado de la concentración urbana compacta.",
contextoPlusvalia:"Dada la baja actividad de compraventa (predominan las herencias), las liquidaciones de plusvalía son poco frecuentes. El valor catastral del suelo en el casco monumental es excepcionalmente bajo.",
consejo:"Si heredas un inmueble en el casco monumental y planeas rehabilitarlo para uso turístico (casa rural, hotel boutique), solicita la bonificación BIC antes de iniciar las obras. La Diputación de Cáceres ofrece además subvenciones de rehabilitación compatibles.",
valoresCatastrales:[{desc:"Casa casco alto",vc:18000},{desc:"Piso zona nueva",vc:40000},{desc:"Casa reformada centro",vc:48000},{desc:"Finca rústica periurbana",vc:22000}]},

{slug:"extremadura/caceres/miajadas",nombre:"Miajadas",prov:"Cáceres",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.62,ibiR:0.50,basura:80,periodo:"1 oct – 30 nov 2026",
bonFN:"20%",bonSolar:"25%",poblacion:"9.876",
fuente:"DOE nº 241, 18/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://miajadas.sedelectronica.es",
intro:"Miajadas, con 9.876 habitantes, es la capital del tomate en Extremadura. Situada en las Vegas Altas del Guadiana, su economía gira en torno a la agroindustria del tomate de industria y el cultivo de regadío. El mercado inmobiliario es de los más asequibles de la región, con viviendas de 3 dormitorios desde 45.000 €.",
contextoIBI:"El tipo del 0,62% produce cuotas moderadas gracias a los bajos valores catastrales de la zona. La última ponencia de valores data de 2014. Los pisos en el centro urbano tienen valores catastrales de 30.000-45.000 €.",
contextoBasura:"La tarifa de 80 €/año refleja la gestión eficiente a través de la mancomunidad comarcal. El servicio incluye recogida selectiva de envases y papel desde 2024.",
contextoPlusvalia:"Las transmisiones son principalmente hereditarias entre familias agricultoras. El bajo valor del suelo urbano limita significativamente las cuotas de plusvalía.",
consejo:"Los propietarios de naves agroindustriales deben verificar que la clasificación catastral de sus inmuebles es correcta (industrial vs. agrario), ya que el tipo rústico (0,50%) es inferior al urbano (0,62%) y la diferencia puede ser significativa en superficies grandes.",
valoresCatastrales:[{desc:"Piso centro",vc:30000},{desc:"Casa pueblo",vc:35000},{desc:"Vivienda adosada nueva",vc:52000},{desc:"Nave agroindustrial",vc:65000}]},

{slug:"extremadura/badajoz/merida",nombre:"Mérida",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.66,ibiR:0.52,basura:125,periodo:"1 oct – 30 nov 2026",
bonFN:"30%",bonSolar:"30%",poblacion:"59.352",
fuente:"DOE nº 244, 21/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://merida.sedelectronica.es",
intro:"Mérida, capital de Extremadura con 59.352 habitantes, alberga el conjunto arqueológico romano más importante de España, declarado Patrimonio de la Humanidad por la UNESCO. Como sede de la Junta de Extremadura y capital autonómica, concentra empleo público y servicios. Su mercado inmobiliario es el más activo de la región, con precios medios de 1.100 €/m² en vivienda de segunda mano.",
contextoIBI:"El tipo del 0,66% es el más alto de los municipios extremeños de nuestra guía, acorde con su condición de capital. La última revisión catastral (2019) actualizó significativamente los valores en zonas como Nueva Ciudad, Polígono y el entorno del Guadiana. Un piso medio de 90 m² tiene un valor catastral de 55.000-70.000 €.",
contextoBasura:"Con 125 €/año, Mérida tiene la tarifa más alta de Extremadura en nuestra base de datos. La subida de 2025 (+15%) responde a la implantación del quinto contenedor (fracción orgánica) y la construcción de la nueva planta de compostaje comarcal.",
contextoPlusvalia:"Como capital autonómica con mercado activo, las compraventas generan liquidaciones de plusvalía frecuentes. El valor catastral del suelo supone el 48% del total en la zona centro y el 42% en las urbanizaciones periféricas.",
consejo:"Los funcionarios de la Junta de Extremadura que compraron vivienda con préstamo hipotecario de la administración pueden solicitar la bonificación de domiciliación del IBI (3%) a través de la plataforma electrónica municipal sin necesidad de desplazarse.",
valoresCatastrales:[{desc:"Piso 2 hab. centro",vc:52000},{desc:"Piso 3 hab. Nueva Ciudad",vc:68000},{desc:"Chalet adosado periurbano",vc:95000},{desc:"Piso antiguo casco romano",vc:45000}]},

{slug:"extremadura/badajoz/don-benito",nombre:"Don Benito",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.63,ibiR:0.50,basura:92,periodo:"1 oct – 30 nov 2026",
bonFN:"25%",bonSolar:"25%",poblacion:"36.762",
fuente:"DOE nº 243, 20/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://donbenito.sedelectronica.es",
intro:"Don Benito, con 36.762 habitantes, forma junto con Villanueva de la Serena una conurbación de más de 60.000 personas en las Vegas Altas del Guadiana. Es un importante centro agroindustrial y comercial. El proceso de fusión con Villanueva (aprobado en referéndum en 2023) puede alterar las ordenanzas fiscales en los próximos ejercicios.",
contextoIBI:"El tipo del 0,63% es moderado. La fusión municipal con Villanueva de la Serena está prevista para 2027, momento en que se armonizarán los tipos impositivos de ambos municipios. Los valores catastrales se revisaron en 2016.",
contextoBasura:"La tarifa de 92 €/año se ha mantenido estable en los últimos dos años. Tras la fusión, se prevé una tarifa unificada que podría situarse entre 90 € y 95 €.",
contextoPlusvalia:"El mercado inmobiliario es activo para una ciudad de su tamaño. Las transmisiones entre particulares generan liquidaciones frecuentes, especialmente en la zona comercial del centro.",
consejo:"Si estás valorando comprar vivienda en Don Benito o Villanueva, ten en cuenta que tras la fusión municipal (prevista 2027) las ordenanzas fiscales podrían cambiar. Consulta el plan de armonización fiscal publicado por ambos ayuntamientos.",
valoresCatastrales:[{desc:"Piso centro comercial",vc:45000},{desc:"Piso barrio nuevo",vc:55000},{desc:"Casa pueblo reformada",vc:40000},{desc:"Chalet zona residencial",vc:82000}]},

{slug:"extremadura/badajoz/almendralejo",nombre:"Almendralejo",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.64,ibiR:0.51,basura:98,periodo:"1 oct – 30 nov 2026",
bonFN:"25%",bonSolar:"25%",poblacion:"34.130",
fuente:"DOE nº 242, 19/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://almendralejo.sedelectronica.es",
intro:"Almendralejo, la 'Tierra de Barros' con 34.130 habitantes, es la capital vitivinícola de Extremadura y sede de la Denominación de Origen Ribera del Guadiana. Su economía combina la viticultura y la industria agroalimentaria con un creciente sector servicios. El casco urbano se ha expandido hacia el norte con urbanizaciones de vivienda unifamiliar.",
contextoIBI:"El tipo del 0,64% genera cuotas moderadas. La ciudad tiene un parque inmobiliario diverso: desde casas de pueblo con patio (valores catastrales de 25.000-35.000 €) hasta chalets en las urbanizaciones del norte (70.000-100.000 €).",
contextoBasura:"La tarifa de 98 €/año incluye el nuevo servicio de recogida selectiva puerta a puerta implantado en 2025 en el centro urbano. Las bodegas y cooperativas pagan tarifas especiales según volumen de residuos.",
contextoPlusvalia:"Las transmisiones de fincas rústicas con calificación urbana en los bordes del casco generan plusvalías significativas cuando se recalifican como suelo urbano.",
consejo:"Los propietarios de bodegas y naves vitivinícolas dentro del casco urbano deben verificar que sus inmuebles tributan como 'industrial' y no como 'comercial', ya que la diferencia de tarifa de basuras puede superar los 200 €/año.",
valoresCatastrales:[{desc:"Casa pueblo con patio",vc:30000},{desc:"Piso 3 hab. centro",vc:48000},{desc:"Chalet norte",vc:85000},{desc:"Nave bodega urbana",vc:55000}]},

{slug:"extremadura/badajoz/villanueva-de-la-serena",nombre:"Villanueva de la Serena",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.63,ibiR:0.50,basura:90,periodo:"1 oct – 30 nov 2026",
bonFN:"25%",bonSolar:"25%",poblacion:"25.938",
fuente:"DOE nº 243, 20/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://villanuevadelaserena.sedelectronica.es",
intro:"Villanueva de la Serena, con 25.938 habitantes, es la segunda ciudad de las Vegas Altas y forma conurbación con Don Benito. Conocida como cuna de Pedro de Valdivia, fundador de Santiago de Chile, la ciudad basa su economía en la agricultura de regadío y los servicios. El referéndum de fusión con Don Benito (2023) aprobó la unión prevista para 2027.",
contextoIBI:"El tipo del 0,63% es idéntico al de Don Benito, lo que facilitará la armonización post-fusión. Los valores catastrales son ligeramente inferiores a los de Don Benito, con pisos de 3 dormitorios entre 40.000 € y 55.000 € de valor catastral.",
contextoBasura:"La tarifa de 90 €/año es 2 € inferior a la de Don Benito. La gestión conjunta del servicio de basuras ya se realiza a través de un consorcio comarcal.",
contextoPlusvalia:"El mercado inmobiliario es más moderado que el de Don Benito. Las transmisiones hereditarias predominan sobre las compraventas.",
consejo:"Si tienes propiedades en ambos municipios (Don Benito y Villanueva), la fusión de 2027 simplificará la gestión tributaria pero no reducirá automáticamente los importes. Solicita ahora las bonificaciones pendientes antes del cambio de ordenanzas.",
valoresCatastrales:[{desc:"Piso centro",vc:40000},{desc:"Piso 3 hab. zona nueva",vc:52000},{desc:"Casa pueblo",vc:35000},{desc:"Chalet urbanización",vc:75000}]},

{slug:"extremadura/badajoz/zafra",nombre:"Zafra",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.63,ibiR:0.50,basura:85,periodo:"1 oct – 30 nov 2026",
bonFN:"20%",bonSolar:"25%",poblacion:"16.840",
fuente:"DOE nº 241, 18/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://zafra.sedelectronica.es",
intro:"Zafra, 'la Sevilla chica' con 16.840 habitantes, es la capital comercial del sur de Badajoz. Su Feria Internacional Ganadera (FIG) es la más importante del sector en el suroeste peninsular. El casco histórico, con el Alcázar de los Duques de Feria y la Plaza Grande, conserva un trazado medieval de gran valor.",
contextoIBI:"El tipo del 0,63% genera cuotas modestas gracias a unos valores catastrales contenidos. La ponencia de valores de 2012 no se ha actualizado, lo que beneficia a los propietarios.",
contextoBasura:"La tarifa de 85 €/año es competitiva. El servicio se gestiona de forma mancomunada con otros municipios de la comarca.",
contextoPlusvalia:"El mercado inmobiliario zafrense se concentra en el casco urbano consolidado. Las transmisiones de locales comerciales en la zona de la Plaza Grande generan plusvalías relevantes por el alto valor del suelo.",
consejo:"Durante la Feria de Zafra (octubre), los alquileres temporales de viviendas pueden generar obligaciones tributarias adicionales. Si alquilas tu vivienda durante la feria, decláralo como rendimiento del capital inmobiliario en el IRPF.",
valoresCatastrales:[{desc:"Piso centro histórico",vc:32000},{desc:"Piso zona nueva",vc:45000},{desc:"Local comercial Plaza",vc:62000},{desc:"Casa pueblo reformada",vc:38000}]},

{slug:"extremadura/badajoz/montijo",nombre:"Montijo",prov:"Badajoz",ccaa:"Extremadura",ccaaSlug:"extremadura",
ibiU:0.62,ibiR:0.49,basura:84,periodo:"1 oct – 30 nov 2026",
bonFN:"20%",bonSolar:"25%",poblacion:"15.872",
fuente:"DOE nº 240, 17/12/2025",fuenteUrl:"https://doe.juntaex.es",sedeUrl:"https://montijo.sedelectronica.es",
intro:"Montijo, con 15.872 habitantes, se ubica en las Vegas Bajas del Guadiana, a 25 km de Mérida y 40 km de Badajoz. Su posición estratégica entre ambas capitales, reforzada por la autovía A-5, la convierte en una localidad residencial atractiva para trabajadores de ambas ciudades. La agricultura de regadío (arroz, tomate, maíz) sigue siendo un pilar económico.",
contextoIBI:"El tipo del 0,62% es moderado. Los valores catastrales reflejan un mercado inmobiliario asequible, con pisos de 3 dormitorios entre 35.000 € y 50.000 € de valor catastral.",
contextoBasura:"Con 84 €/año, Montijo ofrece una de las tarifas más competitivas de la provincia de Badajoz.",
contextoPlusvalia:"Las transmisiones son moderadas. La proximidad a Mérida ha generado un leve aumento de compraventas en los últimos años por compradores que buscan precios más bajos que en la capital.",
consejo:"Si trabajas en Mérida pero vives en Montijo, compara el coste fiscal total (IBI + basuras + IRPF por desplazamiento) con el ahorro en precio de la vivienda. En muchos casos, la diferencia de IBI compensa sobradamente el precio más bajo de compra.",
valoresCatastrales:[{desc:"Piso 2 hab. centro",vc:32000},{desc:"Piso 3 hab.",vc:44000},{desc:"Casa pueblo",vc:30000},{desc:"Vivienda unifamiliar",vc:65000}]}
];
