// Municipal data Part 2: CLM, Aragón, CyL
module.exports = [
{slug:"castilla-la-mancha/toledo/talavera-de-la-reina",nombre:"Talavera de la Reina",prov:"Toledo",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.68,ibiR:0.55,basura:142,periodo:"15 sep – 15 nov 2026",bonFN:"30%",bonSolar:"30%",poblacion:"83.303",
fuente:"DOCM nº 252, 22/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://talavera.sedelectronica.es",
intro:"Talavera de la Reina, con 83.303 habitantes, es la segunda ciudad de Castilla-La Mancha y la mayor de la provincia de Toledo. Famosa por su cerámica declarada Patrimonio Inmaterial de la Humanidad (2019), la ciudad ha experimentado una transformación urbanística con nuevos desarrollos en la zona norte (Puerta de Cuartos). Su mercado inmobiliario muestra una recuperación gradual tras la crisis, con precios medios de 900 €/m².",
contextoIBI:"El tipo del 0,68% es el más alto de nuestra guía, reflejo de la necesidad de financiación de una ciudad con servicios propios de capital provincial. La ponencia de valores de 2020 actualizó significativamente los inmuebles de la zona nueva, mientras que el casco antiguo mantiene valores moderados. Un piso medio de 90 m² tiene un valor catastral entre 55.000 € y 85.000 €.",
contextoBasura:"La tarifa de 142 €/año es la más alta de Castilla-La Mancha en nuestra guía. La subida de 2025 (+18%) se debe a la construcción de la nueva planta de tratamiento de residuos de la Mancomunidad de la Campana de Oropesa y la implantación del contenedor marrón (orgánico).",
contextoPlusvalia:"Talavera tiene un mercado inmobiliario activo con transmisiones frecuentes. El valor catastral del suelo representa el 50% del total en el centro y el 45% en zonas residenciales periféricas.",
consejo:"Si eres ceramista con taller en el casco urbano, verifica que tu inmueble está clasificado como 'industrial-artesanal' y no como 'comercial' en el Catastro, ya que la tarifa de basuras para talleres artesanales es un 30% inferior.",
valoresCatastrales:[{desc:"Piso casco antiguo",vc:45000},{desc:"Piso 3 hab. centro",vc:65000},{desc:"Piso zona norte nueva",vc:82000},{desc:"Chalet periurbano",vc:110000}]},

{slug:"castilla-la-mancha/toledo/illescas",nombre:"Illescas",prov:"Toledo",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.60,ibiR:0.48,basura:108,periodo:"15 sep – 15 nov 2026",bonFN:"25%",bonSolar:"30%",poblacion:"28.642",
fuente:"DOCM nº 250, 20/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://illescas.sedelectronica.es",
intro:"Illescas, con 28.642 habitantes, es uno de los municipios de mayor crecimiento demográfico de Castilla-La Mancha gracias a su proximidad a Madrid (35 km por la A-42). Su desarrollo urbanístico explosivo desde 2000 ha transformado el pueblo agrícola en una ciudad residencial con grandes polígonos industriales y logísticos. El parque empresarial de El Señorío atrae a multinacionales.",
contextoIBI:"El tipo del 0,60% es relativamente bajo, pero los valores catastrales son elevados para la región debido a la revisión de 2021 que reflejó la revalorización inmobiliaria. Un piso nuevo de 3 dormitorios tiene un valor catastral de 85.000-110.000 €, generando cuotas de 510-660 €/año.",
contextoBasura:"La tarifa de 108 €/año refleja los costes del servicio en un municipio de rápido crecimiento que ha tenido que dimensionar sus infraestructuras de recogida a la nueva población.",
contextoPlusvalia:"El intenso mercado de compraventa (muchos residentes que trabajan en Madrid) genera numerosas liquidaciones de plusvalía. Los inmuebles adquiridos antes de 2008 han acumulado incrementos de valor significativos.",
consejo:"Si te has mudado desde Madrid y compraste vivienda en Illescas, compara el ahorro total: aunque el IBI sea menor en tipo, los valores catastrales revisados pueden hacer que la cuota sea similar. Solicita la bonificación de domiciliación cuanto antes.",
valoresCatastrales:[{desc:"Piso 2 hab. zona antigua",vc:55000},{desc:"Piso 3 hab. urbanización nueva",vc:92000},{desc:"Chalet adosado",vc:115000},{desc:"Nave polígono El Señorío",vc:180000}]},

{slug:"castilla-la-mancha/toledo/sesena",nombre:"Seseña",prov:"Toledo",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.58,ibiR:0.47,basura:105,periodo:"15 sep – 15 nov 2026",bonFN:"25%",bonSolar:"25%",poblacion:"28.156",
fuente:"DOCM nº 250, 20/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://sesena.sedelectronica.es",
intro:"Seseña, con 28.156 habitantes, pasó de 8.000 a 28.000 habitantes en dos décadas gracias al desarrollo urbanístico de Seseña Nuevo, una macrourbanización dormitorio de Madrid. El municipio combina el casco antiguo (Seseña Viejo) con la zona nueva, generando dos realidades catastrales muy diferentes.",
contextoIBI:"El tipo del 0,58% es el más bajo de la provincia de Toledo, una decisión política para atraer residentes. Sin embargo, los valores catastrales de Seseña Nuevo son altos (90.000-130.000 € para pisos nuevos), compensando el tipo bajo.",
contextoBasura:"La tarifa de 105 €/año se aplica uniformemente a Seseña Viejo y Nuevo. El servicio en la zona nueva requiere mayor frecuencia de recogida por la alta densidad residencial.",
contextoPlusvalia:"Las compraventas son muy frecuentes en Seseña Nuevo (mercado residencial activo). Los inmuebles comprados durante la burbuja (2005-2008) pueden generar plusvalías negativas si se venden por debajo del precio de adquisición.",
consejo:"Si compraste vivienda en Seseña entre 2005 y 2010 y la vendes ahora por menos de lo que pagaste, no tienes que pagar plusvalía municipal. Aporta ambas escrituras al Ayuntamiento para acreditar la ausencia de incremento de valor.",
valoresCatastrales:[{desc:"Piso Seseña Viejo",vc:42000},{desc:"Piso 2 hab. Seseña Nuevo",vc:75000},{desc:"Piso 3 hab. Seseña Nuevo",vc:98000},{desc:"Chalet adosado",vc:125000}]},

{slug:"castilla-la-mancha/ciudad-real/puertollano",nombre:"Puertollano",prov:"Ciudad Real",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.67,ibiR:0.54,basura:118,periodo:"1 oct – 30 nov 2026",bonFN:"25%",bonSolar:"25%",poblacion:"47.035",
fuente:"DOCM nº 251, 21/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://puertollano.sedelectronica.es",
intro:"Puertollano, con 47.035 habitantes, es la segunda ciudad de Ciudad Real y un importante polo industrial y energético. Sede de la refinería de Repsol y del Centro Nacional del Hidrógeno, la ciudad ha diversificado su economía hacia las energías renovables. El mercado inmobiliario refleja la dependencia industrial, con precios que fluctúan según la coyuntura del sector.",
contextoIBI:"El tipo del 0,67% es alto para la provincia. Los valores catastrales se revisaron en 2017. Los inmuebles cercanos al complejo industrial tienen valores catastrales más bajos por la proximidad a actividad contaminante, mientras que los barrios residenciales del este (La Fraternidad, Libertad) tienen valores superiores.",
contextoBasura:"La tarifa de 118 €/año refleja los costes medioambientales adicionales de gestión de residuos en un municipio con actividad industrial intensiva.",
contextoPlusvalia:"El mercado de compraventa es moderado. Los trabajadores de Repsol que se jubilan y se trasladan a otras ciudades generan transmisiones frecuentes.",
consejo:"Si instalas placas solares para autoconsumo, la bonificación del 25% en el IBI durante 3 años puede amortizar parte de la inversión. Además, Puertollano ofrece subvenciones municipales adicionales para instalaciones renovables en vivienda.",
valoresCatastrales:[{desc:"Piso barrio industrial",vc:38000},{desc:"Piso 3 hab. centro",vc:55000},{desc:"Piso barrio residencial",vc:62000},{desc:"Chalet zona este",vc:88000}]},

{slug:"castilla-la-mancha/ciudad-real/tomelloso",nombre:"Tomelloso",prov:"Ciudad Real",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.65,ibiR:0.52,basura:110,periodo:"1 oct – 30 nov 2026",bonFN:"25%",bonSolar:"25%",poblacion:"36.280",
fuente:"DOCM nº 251, 21/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://tomelloso.sedelectronica.es",
intro:"Tomelloso, con 36.280 habitantes, es la capital del vino de La Mancha y alberga el mayor número de bodegas por habitante de España. Su economía combina la vitivinicultura con industria del mueble y un creciente sector servicios. La ciudad tiene un urbanismo compacto con pocas urbanizaciones periféricas.",
contextoIBI:"El tipo del 0,65% genera cuotas moderadas. Los valores catastrales son contenidos, con pisos de 3 dormitorios entre 40.000 € y 60.000 € de valor catastral. Las bodegas urbanas tributan como uso industrial.",
contextoBasura:"La tarifa de 110 €/año se ha incrementado un 12% respecto a 2024 por la implantación del nuevo servicio de recogida puerta a puerta en el centro.",
contextoPlusvalia:"Las transmisiones de bodegas y terrenos urbanos periféricos generan las plusvalías más relevantes del municipio, dado el alto valor del suelo en parcelas grandes.",
consejo:"Los propietarios de bodegas en desuso dentro del casco urbano que planeen reconvertirlas a vivienda deben solicitar el cambio de uso catastral antes de la rehabilitación, ya que el valor catastral como vivienda será diferente y afectará al IBI futuro.",
valoresCatastrales:[{desc:"Piso centro",vc:42000},{desc:"Piso 3 hab.",vc:55000},{desc:"Bodega urbana",vc:48000},{desc:"Chalet",vc:78000}]},

{slug:"castilla-la-mancha/ciudad-real/alcazar-de-san-juan",nombre:"Alcázar de San Juan",prov:"Ciudad Real",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.64,ibiR:0.51,basura:105,periodo:"1 oct – 30 nov 2026",bonFN:"25%",bonSolar:"25%",poblacion:"30.662",
fuente:"DOCM nº 250, 20/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://alcazardesanjuan.sedelectronica.es",
intro:"Alcázar de San Juan, con 30.662 habitantes, es un importante nudo ferroviario en el corazón de La Mancha. Reclama ser la verdadera patria de Cervantes y mantiene una activa vida cultural. La ciudad es un centro de servicios comarcal con un mercado inmobiliario asequible donde los pisos de 3 dormitorios oscilan entre 50.000 € y 90.000 €.",
contextoIBI:"El tipo del 0,64% es moderado. Los valores catastrales no se han revisado desde 2014, manteniéndose por debajo del valor de mercado en la mayoría de zonas.",
contextoBasura:"La tarifa de 105 €/año incluye el servicio de recogida 6 días/semana y el punto limpio municipal.",
contextoPlusvalia:"Las transmisiones son moderadas, con predominio de herencias sobre compraventas.",
consejo:"Si tu inmueble tiene más de 25 años y no se ha hecho revisión catastral de la zona, el valor catastral puede estar significativamente por debajo del de mercado. Esto te beneficia en IBI pero te perjudica si vendes (la plusvalía se calcula sobre el catastral del suelo).",
valoresCatastrales:[{desc:"Piso antiguo centro",vc:35000},{desc:"Piso 3 hab.",vc:50000},{desc:"Casa pueblo reformada",vc:42000},{desc:"Vivienda unifamiliar",vc:72000}]},

{slug:"castilla-la-mancha/guadalajara/azuqueca-de-henares",nombre:"Azuqueca de Henares",prov:"Guadalajara",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.61,ibiR:0.49,basura:112,periodo:"1 oct – 30 nov 2026",bonFN:"30%",bonSolar:"30%",poblacion:"36.518",
fuente:"DOCM nº 252, 22/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://azuqueca.sedelectronica.es",
intro:"Azuqueca de Henares, con 36.518 habitantes, pertenece al corredor del Henares y es funcionalmente parte del área metropolitana de Madrid-Guadalajara. Su explosivo crecimiento demográfico (de 8.000 habitantes en 1990 a 36.000 actuales) ha convertido el antiguo pueblo en una ciudad residencial con excelentes comunicaciones ferroviarias (Cercanías) y por autovía (A-2).",
contextoIBI:"El tipo del 0,61% es moderado, pero los valores catastrales son de los más altos de Castilla-La Mancha debido a la influencia del mercado madrileño. Un piso de 3 dormitorios tiene un valor catastral de 80.000-120.000 €, generando cuotas entre 488 € y 732 €.",
contextoBasura:"La tarifa de 112 €/año se justifica por los elevados estándares del servicio, comparable al de municipios del área metropolitana de Madrid.",
contextoPlusvalia:"El mercado es muy activo: compraventas frecuentes entre residentes que se mudan dentro del corredor del Henares. Los inmuebles comprados antes de 2015 han acumulado incrementos de valor importantes.",
consejo:"Si trabajas en Madrid y vives en Azuqueca, recuerda que el abono transporte de la zona C de Cercanías es deducible como gasto de desplazamiento. Además, la bonificación por energía solar (30%) es de las más generosas del corredor del Henares.",
valoresCatastrales:[{desc:"Piso 2 hab. antiguo",vc:62000},{desc:"Piso 3 hab. urbanización",vc:95000},{desc:"Ático dúplex",vc:118000},{desc:"Chalet adosado",vc:140000}]},

{slug:"castilla-la-mancha/albacete/hellin",nombre:"Hellín",prov:"Albacete",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.64,ibiR:0.51,basura:95,periodo:"1 oct – 30 nov 2026",bonFN:"20%",bonSolar:"25%",poblacion:"30.368",
fuente:"DOCM nº 251, 21/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://hellin.sedelectronica.es",
intro:"Hellín, con 30.368 habitantes, es la segunda ciudad de Albacete y famosa internacionalmente por su Semana Santa (declarada de Interés Turístico Internacional). La economía local combina agricultura, textil y turismo cultural. Su mercado inmobiliario es uno de los más asequibles de Castilla-La Mancha.",
contextoIBI:"El tipo del 0,64% genera cuotas bajas por los reducidos valores catastrales de la zona. Un piso de 3 dormitorios tiene un valor catastral medio de 35.000-50.000 €.",
contextoBasura:"La tarifa de 95 €/año es moderada y se ha mantenido estable en los últimos tres ejercicios.",
contextoPlusvalia:"Las transmisiones hereditarias predominan. El bajo valor del suelo urbano limita las cuotas de plusvalía.",
consejo:"Si tienes una vivienda en el casco histórico y participas activamente en la Semana Santa (cofradía con sede en tu inmueble), consulta si existe alguna exención o bonificación por uso cultural o religioso del inmueble.",
valoresCatastrales:[{desc:"Piso casco antiguo",vc:28000},{desc:"Piso 3 hab. centro",vc:42000},{desc:"Casa pueblo",vc:32000},{desc:"Vivienda nueva",vc:58000}]},

{slug:"castilla-la-mancha/albacete/almansa",nombre:"Almansa",prov:"Albacete",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.63,ibiR:0.50,basura:92,periodo:"1 oct – 30 nov 2026",bonFN:"20%",bonSolar:"25%",poblacion:"24.786",
fuente:"DOCM nº 251, 21/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://almansa.sedelectronica.es",
intro:"Almansa, con 24.786 habitantes, es conocida por su imponente castillo y por la histórica batalla de 1707. Ciudad industrial centrada en el calzado (más de 200 empresas del sector), Almansa combina tradición zapatera con una creciente diversificación hacia la logística y las renovables.",
contextoIBI:"El tipo del 0,63% es moderado. Las naves industriales del sector calzado representan una parte significativa de la base imponible del municipio.",
contextoBasura:"La tarifa de 92 €/año incluye servicio de recogida industrial adaptado a las necesidades de las fábricas de calzado.",
contextoPlusvalia:"Las transmisiones de naves industriales entre empresas del sector calzado generan las plusvalías más relevantes.",
consejo:"Los fabricantes de calzado con naves en los polígonos industriales pueden solicitar la bonificación de inicio de actividad empresarial (hasta 50%) durante los primeros 3 años si amplían o relocalizan su producción.",
valoresCatastrales:[{desc:"Piso centro",vc:32000},{desc:"Piso 3 hab.",vc:45000},{desc:"Nave industrial calzado",vc:75000},{desc:"Casa pueblo",vc:28000}]},

{slug:"castilla-la-mancha/cuenca/cuenca",nombre:"Cuenca",prov:"Cuenca",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.66,ibiR:0.53,basura:120,periodo:"1 oct – 30 nov 2026",bonFN:"25%",bonSolar:"25%",poblacion:"54.690",
fuente:"DOCM nº 252, 22/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://cuenca.sedelectronica.es",
intro:"Cuenca, capital provincial con 54.690 habitantes, es Patrimonio de la Humanidad por la UNESCO desde 1996. Sus Casas Colgadas, la Ciudad Encantada y el Museo de Arte Abstracto la convierten en un destino turístico de primer orden. El casco antiguo (parte alta) presenta un mercado inmobiliario singular, con viviendas de difícil acceso y reformas costosas.",
contextoIBI:"El tipo del 0,66% es alto para una capital de provincia pequeña. Los inmuebles del casco alto (Patrimonio UNESCO) tienen valores catastrales reducidos por antigüedad, pero la zona nueva presenta valores más altos.",
contextoBasura:"La tarifa de 120 €/año es elevada, parcialmente debido al coste extra de recogida en el casco histórico con vehículos especiales adaptados a las calles estrechas.",
contextoPlusvalia:"Las ventas de inmuebles en el casco antiguo a inversores turísticos han generado plusvalías significativas en los últimos años por la revalorización turística.",
consejo:"Si compras un inmueble en el casco antiguo de Cuenca para rehabilitarlo como alojamiento turístico, puedes solicitar la bonificación BIC (hasta 90%) durante los años de rehabilitación, compatible con las subvenciones del Plan de Patrimonio.",
valoresCatastrales:[{desc:"Casa casco antiguo",vc:35000},{desc:"Piso parte baja",vc:52000},{desc:"Piso zona nueva",vc:65000},{desc:"Vivienda turística casco",vc:48000}]},

{slug:"castilla-la-mancha/cuenca/tarancon",nombre:"Tarancón",prov:"Cuenca",ccaa:"Castilla-La Mancha",ccaaSlug:"castilla-la-mancha",
ibiU:0.62,ibiR:0.50,basura:98,periodo:"1 oct – 30 nov 2026",bonFN:"20%",bonSolar:"25%",poblacion:"16.438",
fuente:"DOCM nº 250, 20/12/2025",fuenteUrl:"https://docm.jccm.es",sedeUrl:"https://tarancon.sedelectronica.es",
intro:"Tarancón, con 16.438 habitantes, es el municipio más poblado de la provincia de Cuenca fuera de la capital. Su posición en el cruce de la A-3 (Madrid-Valencia) y la A-40 (autovía de Castilla-La Mancha) lo convierte en un nudo logístico importante y una opción residencial para trabajadores del corredor Madrid-Valencia.",
contextoIBI:"El tipo del 0,62% es moderado. Los valores catastrales reflejan un mercado inmobiliario contenido pero en crecimiento por la mejora de las comunicaciones.",
contextoBasura:"La tarifa de 98 €/año se gestiona a través de la Mancomunidad de Servicios de la comarca.",
contextoPlusvalia:"Las transmisiones han aumentado en los últimos años por la llegada de nuevos residentes desde Madrid y el corredor del Henares.",
consejo:"Si te has mudado a Tarancón desde Madrid y mantienes empadronamiento en ambos municipios, regulariza tu situación. El IBI de vivienda habitual puede tener bonificaciones que solo aplican con empadronamiento.",
valoresCatastrales:[{desc:"Piso centro",vc:35000},{desc:"Piso 3 hab. zona nueva",vc:52000},{desc:"Casa pueblo",vc:30000},{desc:"Chalet periurbano",vc:68000}]}
];
